version: '3.8'

services:
  # FastAPI Application
  app:
    build: .
    container_name: ticket-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/ticket_app
      - SECRET_KEY=your-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app
    networks:
      - ticket-network
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ticket-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ticket_app
    volumes:
      - mongodb_data:/data/db
    networks:
      - ticket-network
    restart: unless-stopped

  # MongoDB Express (Web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: ticket-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - ticket-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  ticket-network:
    driver: bridge
